[build.environment]
SECRETS_SCAN_OMIT_KEYS = "REACT_APP_CONTACT_EMAIL,REACT_APP_CONTACT_PHONE,EMAIL,EMAIL_PASS"

[build]
  base = "Frontend"
  command = "npm run build"
  publish = "Frontend/build"
  functions = "netlify/functions"
